// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: daemon/proto/daemon.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DestinationType int32

const (
	DestinationType_FILE     DestinationType = 0
	DestinationType_CLAUDE   DestinationType = 1
	DestinationType_VSCODE   DestinationType = 2
	DestinationType_CURSOR   DestinationType = 3
	DestinationType_WINDSURF DestinationType = 4
	DestinationType_ZED      DestinationType = 5
	DestinationType_CUSTOM   DestinationType = 99
)

// Enum value maps for DestinationType.
var (
	DestinationType_name = map[int32]string{
		0:  "FILE",
		1:  "CLAUDE",
		2:  "VSCODE",
		3:  "CURSOR",
		4:  "WINDSURF",
		5:  "ZED",
		99: "CUSTOM",
	}
	DestinationType_value = map[string]int32{
		"FILE":     0,
		"CLAUDE":   1,
		"VSCODE":   2,
		"CURSOR":   3,
		"WINDSURF": 4,
		"ZED":      5,
		"CUSTOM":   99,
	}
)

func (x DestinationType) Enum() *DestinationType {
	p := new(DestinationType)
	*p = x
	return p
}

func (x DestinationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DestinationType) Descriptor() protoreflect.EnumDescriptor {
	return file_daemon_proto_daemon_proto_enumTypes[0].Descriptor()
}

func (DestinationType) Type() protoreflect.EnumType {
	return &file_daemon_proto_daemon_proto_enumTypes[0]
}

func (x DestinationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DestinationType.Descriptor instead.
func (DestinationType) EnumDescriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{0}
}

type ChangeType int32

const (
	ChangeType_ADD       ChangeType = 0
	ChangeType_UPDATE    ChangeType = 1
	ChangeType_REMOVE    ChangeType = 2
	ChangeType_NO_CHANGE ChangeType = 3
)

// Enum value maps for ChangeType.
var (
	ChangeType_name = map[int32]string{
		0: "ADD",
		1: "UPDATE",
		2: "REMOVE",
		3: "NO_CHANGE",
	}
	ChangeType_value = map[string]int32{
		"ADD":       0,
		"UPDATE":    1,
		"REMOVE":    2,
		"NO_CHANGE": 3,
	}
)

func (x ChangeType) Enum() *ChangeType {
	p := new(ChangeType)
	*p = x
	return p
}

func (x ChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_daemon_proto_daemon_proto_enumTypes[1].Descriptor()
}

func (ChangeType) Type() protoreflect.EnumType {
	return &file_daemon_proto_daemon_proto_enumTypes[1]
}

func (x ChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeType.Descriptor instead.
func (ChangeType) EnumDescriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{1}
}

type EventType int32

const (
	EventType_CONFIG_CHANGE    EventType = 0
	EventType_SYNC_COMPLETE    EventType = 1
	EventType_ERROR            EventType = 2
	EventType_AUTO_SYNC_STATUS EventType = 3
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "CONFIG_CHANGE",
		1: "SYNC_COMPLETE",
		2: "ERROR",
		3: "AUTO_SYNC_STATUS",
	}
	EventType_value = map[string]int32{
		"CONFIG_CHANGE":    0,
		"SYNC_COMPLETE":    1,
		"ERROR":            2,
		"AUTO_SYNC_STATUS": 3,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_daemon_proto_daemon_proto_enumTypes[2].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_daemon_proto_daemon_proto_enumTypes[2]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{2}
}

// Server types
type ServerConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transport     string                 `protobuf:"bytes,1,opt,name=transport,proto3" json:"transport,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Env           map[string]string      `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig.ProtoReflect.Descriptor instead.
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *ServerConfig) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *ServerConfig) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ServerConfig) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ServerConfig) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ServerConfig) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ServerConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ServerConfig) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ServerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Config        *ServerConfig          `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *ServerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServerInfo) GetConfig() *ServerConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ServerInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ServerInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ServerInfo) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// Requests
type AddServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Config        *ServerConfig          `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddServerRequest) Reset() {
	*x = AddServerRequest{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddServerRequest) ProtoMessage() {}

func (x *AddServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddServerRequest.ProtoReflect.Descriptor instead.
func (*AddServerRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *AddServerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddServerRequest) GetConfig() *ServerConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Config        *ServerConfig          `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServerRequest) Reset() {
	*x = UpdateServerRequest{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServerRequest) ProtoMessage() {}

func (x *UpdateServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServerRequest.ProtoReflect.Descriptor instead.
func (*UpdateServerRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateServerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateServerRequest) GetConfig() *ServerConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type RemoveServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveServerRequest) Reset() {
	*x = RemoveServerRequest{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveServerRequest) ProtoMessage() {}

func (x *RemoveServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveServerRequest.ProtoReflect.Descriptor instead.
func (*RemoveServerRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveServerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerRequest) Reset() {
	*x = GetServerRequest{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerRequest) ProtoMessage() {}

func (x *GetServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerRequest.ProtoReflect.Descriptor instead.
func (*GetServerRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{5}
}

func (x *GetServerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EnableServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableServerRequest) Reset() {
	*x = EnableServerRequest{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableServerRequest) ProtoMessage() {}

func (x *EnableServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableServerRequest.ProtoReflect.Descriptor instead.
func (*EnableServerRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{6}
}

func (x *EnableServerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DisableServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableServerRequest) Reset() {
	*x = DisableServerRequest{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableServerRequest) ProtoMessage() {}

func (x *DisableServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableServerRequest.ProtoReflect.Descriptor instead.
func (*DisableServerRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{7}
}

func (x *DisableServerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListServersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *ServerFilter          `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServersRequest) Reset() {
	*x = ListServersRequest{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServersRequest) ProtoMessage() {}

func (x *ListServersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServersRequest.ProtoReflect.Descriptor instead.
func (*ListServersRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{8}
}

func (x *ListServersRequest) GetFilter() *ServerFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ServerFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnabledOnly   bool                   `protobuf:"varint,1,opt,name=enabled_only,json=enabledOnly,proto3" json:"enabled_only,omitempty"`
	Transport     string                 `protobuf:"bytes,2,opt,name=transport,proto3" json:"transport,omitempty"`
	NamePattern   string                 `protobuf:"bytes,3,opt,name=name_pattern,json=namePattern,proto3" json:"name_pattern,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFilter) Reset() {
	*x = ServerFilter{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFilter) ProtoMessage() {}

func (x *ServerFilter) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFilter.ProtoReflect.Descriptor instead.
func (*ServerFilter) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{9}
}

func (x *ServerFilter) GetEnabledOnly() bool {
	if x != nil {
		return x.EnabledOnly
	}
	return false
}

func (x *ServerFilter) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *ServerFilter) GetNamePattern() string {
	if x != nil {
		return x.NamePattern
	}
	return ""
}

func (x *ServerFilter) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// Responses
type ServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *ServerInfo            `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerResponse) Reset() {
	*x = ServerResponse{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerResponse) ProtoMessage() {}

func (x *ServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerResponse.ProtoReflect.Descriptor instead.
func (*ServerResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{10}
}

func (x *ServerResponse) GetServer() *ServerInfo {
	if x != nil {
		return x.Server
	}
	return nil
}

type ListServersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Servers       []*ServerInfo          `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServersResponse) Reset() {
	*x = ListServersResponse{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServersResponse) ProtoMessage() {}

func (x *ListServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServersResponse.ProtoReflect.Descriptor instead.
func (*ListServersResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{11}
}

func (x *ListServersResponse) GetServers() []*ServerInfo {
	if x != nil {
		return x.Servers
	}
	return nil
}

// Destination management
type RegisterDestinationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          DestinationType        `protobuf:"varint,2,opt,name=type,proto3,enum=daemon.DestinationType" json:"type,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Options       map[string]string      `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDestinationRequest) Reset() {
	*x = RegisterDestinationRequest{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDestinationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDestinationRequest) ProtoMessage() {}

func (x *RegisterDestinationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDestinationRequest.ProtoReflect.Descriptor instead.
func (*RegisterDestinationRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterDestinationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterDestinationRequest) GetType() DestinationType {
	if x != nil {
		return x.Type
	}
	return DestinationType_FILE
}

func (x *RegisterDestinationRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RegisterDestinationRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type RemoveDestinationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveDestinationRequest) Reset() {
	*x = RemoveDestinationRequest{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDestinationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDestinationRequest) ProtoMessage() {}

func (x *RemoveDestinationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDestinationRequest.ProtoReflect.Descriptor instead.
func (*RemoveDestinationRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveDestinationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListDestinationsResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Destinations  map[string]*DestinationInfo `protobuf:"bytes,1,rep,name=destinations,proto3" json:"destinations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDestinationsResponse) Reset() {
	*x = ListDestinationsResponse{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDestinationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDestinationsResponse) ProtoMessage() {}

func (x *ListDestinationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDestinationsResponse.ProtoReflect.Descriptor instead.
func (*ListDestinationsResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{14}
}

func (x *ListDestinationsResponse) GetDestinations() map[string]*DestinationInfo {
	if x != nil {
		return x.Destinations
	}
	return nil
}

type DestinationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          DestinationType        `protobuf:"varint,2,opt,name=type,proto3,enum=daemon.DestinationType" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Available     bool                   `protobuf:"varint,4,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestinationInfo) Reset() {
	*x = DestinationInfo{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestinationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestinationInfo) ProtoMessage() {}

func (x *DestinationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestinationInfo.ProtoReflect.Descriptor instead.
func (*DestinationInfo) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{15}
}

func (x *DestinationInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DestinationInfo) GetType() DestinationType {
	if x != nil {
		return x.Type
	}
	return DestinationType_FILE
}

func (x *DestinationInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DestinationInfo) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

// Sync operations
type SyncToRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Destination   string                 `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	Options       *SyncOptions           `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncToRequest) Reset() {
	*x = SyncToRequest{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncToRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncToRequest) ProtoMessage() {}

func (x *SyncToRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncToRequest.ProtoReflect.Descriptor instead.
func (*SyncToRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{16}
}

func (x *SyncToRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *SyncToRequest) GetOptions() *SyncOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type SyncToMultipleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Destinations  []string               `protobuf:"bytes,1,rep,name=destinations,proto3" json:"destinations,omitempty"`
	Options       *SyncOptions           `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncToMultipleRequest) Reset() {
	*x = SyncToMultipleRequest{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncToMultipleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncToMultipleRequest) ProtoMessage() {}

func (x *SyncToMultipleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncToMultipleRequest.ProtoReflect.Descriptor instead.
func (*SyncToMultipleRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{17}
}

func (x *SyncToMultipleRequest) GetDestinations() []string {
	if x != nil {
		return x.Destinations
	}
	return nil
}

func (x *SyncToMultipleRequest) GetOptions() *SyncOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type PreviewSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Destination   string                 `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewSyncRequest) Reset() {
	*x = PreviewSyncRequest{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewSyncRequest) ProtoMessage() {}

func (x *PreviewSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewSyncRequest.ProtoReflect.Descriptor instead.
func (*PreviewSyncRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{18}
}

func (x *PreviewSyncRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

type SyncOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Force         bool                   `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`
	Backup        bool                   `protobuf:"varint,2,opt,name=backup,proto3" json:"backup,omitempty"`
	DryRun        bool                   `protobuf:"varint,3,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncOptions) Reset() {
	*x = SyncOptions{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncOptions) ProtoMessage() {}

func (x *SyncOptions) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncOptions.ProtoReflect.Descriptor instead.
func (*SyncOptions) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{19}
}

func (x *SyncOptions) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *SyncOptions) GetBackup() bool {
	if x != nil {
		return x.Backup
	}
	return false
}

func (x *SyncOptions) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type SyncResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ServersSynced int32                  `protobuf:"varint,3,opt,name=servers_synced,json=serversSynced,proto3" json:"servers_synced,omitempty"`
	Errors        []string               `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResult) Reset() {
	*x = SyncResult{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResult) ProtoMessage() {}

func (x *SyncResult) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResult.ProtoReflect.Descriptor instead.
func (*SyncResult) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{20}
}

func (x *SyncResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SyncResult) GetServersSynced() int32 {
	if x != nil {
		return x.ServersSynced
	}
	return 0
}

func (x *SyncResult) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *SyncResult) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type MultiSyncResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       map[string]*SyncResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TotalSuccess  int32                  `protobuf:"varint,2,opt,name=total_success,json=totalSuccess,proto3" json:"total_success,omitempty"`
	TotalFailed   int32                  `protobuf:"varint,3,opt,name=total_failed,json=totalFailed,proto3" json:"total_failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiSyncResult) Reset() {
	*x = MultiSyncResult{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiSyncResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiSyncResult) ProtoMessage() {}

func (x *MultiSyncResult) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiSyncResult.ProtoReflect.Descriptor instead.
func (*MultiSyncResult) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{21}
}

func (x *MultiSyncResult) GetResults() map[string]*SyncResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *MultiSyncResult) GetTotalSuccess() int32 {
	if x != nil {
		return x.TotalSuccess
	}
	return 0
}

func (x *MultiSyncResult) GetTotalFailed() int32 {
	if x != nil {
		return x.TotalFailed
	}
	return 0
}

type SyncPreview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changes       []*ServerChange        `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
	TotalChanges  int32                  `protobuf:"varint,2,opt,name=total_changes,json=totalChanges,proto3" json:"total_changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncPreview) Reset() {
	*x = SyncPreview{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncPreview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPreview) ProtoMessage() {}

func (x *SyncPreview) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPreview.ProtoReflect.Descriptor instead.
func (*SyncPreview) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{22}
}

func (x *SyncPreview) GetChanges() []*ServerChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *SyncPreview) GetTotalChanges() int32 {
	if x != nil {
		return x.TotalChanges
	}
	return 0
}

type ServerChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          ChangeType             `protobuf:"varint,2,opt,name=type,proto3,enum=daemon.ChangeType" json:"type,omitempty"`
	Before        *ServerConfig          `protobuf:"bytes,3,opt,name=before,proto3" json:"before,omitempty"`
	After         *ServerConfig          `protobuf:"bytes,4,opt,name=after,proto3" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerChange) Reset() {
	*x = ServerChange{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerChange) ProtoMessage() {}

func (x *ServerChange) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerChange.ProtoReflect.Descriptor instead.
func (*ServerChange) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{23}
}

func (x *ServerChange) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServerChange) GetType() ChangeType {
	if x != nil {
		return x.Type
	}
	return ChangeType_ADD
}

func (x *ServerChange) GetBefore() *ServerConfig {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *ServerChange) GetAfter() *ServerConfig {
	if x != nil {
		return x.After
	}
	return nil
}

// Auto-sync
type AutoSyncConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Enabled         bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	WatchIntervalMs int64                  `protobuf:"varint,2,opt,name=watch_interval_ms,json=watchIntervalMs,proto3" json:"watch_interval_ms,omitempty"`
	DebounceDelayMs int64                  `protobuf:"varint,3,opt,name=debounce_delay_ms,json=debounceDelayMs,proto3" json:"debounce_delay_ms,omitempty"`
	TargetWhitelist []string               `protobuf:"bytes,4,rep,name=target_whitelist,json=targetWhitelist,proto3" json:"target_whitelist,omitempty"`
	TargetBlacklist []string               `protobuf:"bytes,5,rep,name=target_blacklist,json=targetBlacklist,proto3" json:"target_blacklist,omitempty"`
	IgnorePatterns  []string               `protobuf:"bytes,6,rep,name=ignore_patterns,json=ignorePatterns,proto3" json:"ignore_patterns,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AutoSyncConfig) Reset() {
	*x = AutoSyncConfig{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoSyncConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoSyncConfig) ProtoMessage() {}

func (x *AutoSyncConfig) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoSyncConfig.ProtoReflect.Descriptor instead.
func (*AutoSyncConfig) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{24}
}

func (x *AutoSyncConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AutoSyncConfig) GetWatchIntervalMs() int64 {
	if x != nil {
		return x.WatchIntervalMs
	}
	return 0
}

func (x *AutoSyncConfig) GetDebounceDelayMs() int64 {
	if x != nil {
		return x.DebounceDelayMs
	}
	return 0
}

func (x *AutoSyncConfig) GetTargetWhitelist() []string {
	if x != nil {
		return x.TargetWhitelist
	}
	return nil
}

func (x *AutoSyncConfig) GetTargetBlacklist() []string {
	if x != nil {
		return x.TargetBlacklist
	}
	return nil
}

func (x *AutoSyncConfig) GetIgnorePatterns() []string {
	if x != nil {
		return x.IgnorePatterns
	}
	return nil
}

type AutoSyncStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Enabled         bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Running         bool                   `protobuf:"varint,2,opt,name=running,proto3" json:"running,omitempty"`
	LastSync        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_sync,json=lastSync,proto3" json:"last_sync,omitempty"`
	WatchIntervalMs int64                  `protobuf:"varint,4,opt,name=watch_interval_ms,json=watchIntervalMs,proto3" json:"watch_interval_ms,omitempty"`
	LastError       string                 `protobuf:"bytes,5,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AutoSyncStatus) Reset() {
	*x = AutoSyncStatus{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoSyncStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoSyncStatus) ProtoMessage() {}

func (x *AutoSyncStatus) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoSyncStatus.ProtoReflect.Descriptor instead.
func (*AutoSyncStatus) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{25}
}

func (x *AutoSyncStatus) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AutoSyncStatus) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *AutoSyncStatus) GetLastSync() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSync
	}
	return nil
}

func (x *AutoSyncStatus) GetWatchIntervalMs() int64 {
	if x != nil {
		return x.WatchIntervalMs
	}
	return 0
}

func (x *AutoSyncStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

// Configuration
type Config struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Version       string                   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Servers       map[string]*ServerConfig `protobuf:"bytes,2,rep,name=servers,proto3" json:"servers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Settings      *Settings                `protobuf:"bytes,3,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{26}
}

func (x *Config) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Config) GetServers() map[string]*ServerConfig {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *Config) GetSettings() *Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type Settings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AutoSync      *AutoSyncSettings      `protobuf:"bytes,1,opt,name=auto_sync,json=autoSync,proto3" json:"auto_sync,omitempty"`
	Backup        *BackupSettings        `protobuf:"bytes,2,opt,name=backup,proto3" json:"backup,omitempty"`
	Validation    *ValidationSettings    `protobuf:"bytes,3,opt,name=validation,proto3" json:"validation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Settings) Reset() {
	*x = Settings{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Settings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settings) ProtoMessage() {}

func (x *Settings) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settings.ProtoReflect.Descriptor instead.
func (*Settings) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{27}
}

func (x *Settings) GetAutoSync() *AutoSyncSettings {
	if x != nil {
		return x.AutoSync
	}
	return nil
}

func (x *Settings) GetBackup() *BackupSettings {
	if x != nil {
		return x.Backup
	}
	return nil
}

func (x *Settings) GetValidation() *ValidationSettings {
	if x != nil {
		return x.Validation
	}
	return nil
}

type AutoSyncSettings struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Enabled         bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	WatchIntervalMs int64                  `protobuf:"varint,2,opt,name=watch_interval_ms,json=watchIntervalMs,proto3" json:"watch_interval_ms,omitempty"`
	DebounceDelayMs int64                  `protobuf:"varint,3,opt,name=debounce_delay_ms,json=debounceDelayMs,proto3" json:"debounce_delay_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AutoSyncSettings) Reset() {
	*x = AutoSyncSettings{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoSyncSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoSyncSettings) ProtoMessage() {}

func (x *AutoSyncSettings) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoSyncSettings.ProtoReflect.Descriptor instead.
func (*AutoSyncSettings) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{28}
}

func (x *AutoSyncSettings) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AutoSyncSettings) GetWatchIntervalMs() int64 {
	if x != nil {
		return x.WatchIntervalMs
	}
	return 0
}

func (x *AutoSyncSettings) GetDebounceDelayMs() int64 {
	if x != nil {
		return x.DebounceDelayMs
	}
	return 0
}

type BackupSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	MaxBackups    int32                  `protobuf:"varint,3,opt,name=max_backups,json=maxBackups,proto3" json:"max_backups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupSettings) Reset() {
	*x = BackupSettings{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupSettings) ProtoMessage() {}

func (x *BackupSettings) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupSettings.ProtoReflect.Descriptor instead.
func (*BackupSettings) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{29}
}

func (x *BackupSettings) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *BackupSettings) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *BackupSettings) GetMaxBackups() int32 {
	if x != nil {
		return x.MaxBackups
	}
	return 0
}

type ValidationSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	StrictMode    bool                   `protobuf:"varint,2,opt,name=strict_mode,json=strictMode,proto3" json:"strict_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationSettings) Reset() {
	*x = ValidationSettings{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationSettings) ProtoMessage() {}

func (x *ValidationSettings) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationSettings.ProtoReflect.Descriptor instead.
func (*ValidationSettings) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{30}
}

func (x *ValidationSettings) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ValidationSettings) GetStrictMode() bool {
	if x != nil {
		return x.StrictMode
	}
	return false
}

type LoadConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadConfigRequest) Reset() {
	*x = LoadConfigRequest{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadConfigRequest) ProtoMessage() {}

func (x *LoadConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadConfigRequest.ProtoReflect.Descriptor instead.
func (*LoadConfigRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{31}
}

func (x *LoadConfigRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Daemon status
type DaemonStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Running           bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	Version           string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	StartTime         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	UptimeSeconds     int64                  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	ActiveConnections int32                  `protobuf:"varint,5,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	AutoSyncRunning   bool                   `protobuf:"varint,6,opt,name=auto_sync_running,json=autoSyncRunning,proto3" json:"auto_sync_running,omitempty"`
	LastError         string                 `protobuf:"bytes,7,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DaemonStatus) Reset() {
	*x = DaemonStatus{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonStatus) ProtoMessage() {}

func (x *DaemonStatus) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonStatus.ProtoReflect.Descriptor instead.
func (*DaemonStatus) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{32}
}

func (x *DaemonStatus) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *DaemonStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DaemonStatus) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *DaemonStatus) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *DaemonStatus) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *DaemonStatus) GetAutoSyncRunning() bool {
	if x != nil {
		return x.AutoSyncRunning
	}
	return false
}

func (x *DaemonStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

// Events
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Types         []EventType            `protobuf:"varint,1,rep,packed,name=types,proto3,enum=daemon.EventType" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{33}
}

func (x *SubscribeRequest) GetTypes() []EventType {
	if x != nil {
		return x.Types
	}
	return nil
}

type Event struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Type      EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=daemon.EventType" json:"type,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Event_ConfigChange
	//	*Event_SyncComplete
	//	*Event_Error
	//	*Event_AutoSync
	Payload       isEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{34}
}

func (x *Event) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_CONFIG_CHANGE
}

func (x *Event) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Event) GetPayload() isEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetConfigChange() *ConfigChangeEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_ConfigChange); ok {
			return x.ConfigChange
		}
	}
	return nil
}

func (x *Event) GetSyncComplete() *SyncCompleteEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_SyncComplete); ok {
			return x.SyncComplete
		}
	}
	return nil
}

func (x *Event) GetError() *ErrorEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Event) GetAutoSync() *AutoSyncEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_AutoSync); ok {
			return x.AutoSync
		}
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_ConfigChange struct {
	ConfigChange *ConfigChangeEvent `protobuf:"bytes,3,opt,name=config_change,json=configChange,proto3,oneof"`
}

type Event_SyncComplete struct {
	SyncComplete *SyncCompleteEvent `protobuf:"bytes,4,opt,name=sync_complete,json=syncComplete,proto3,oneof"`
}

type Event_Error struct {
	Error *ErrorEvent `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

type Event_AutoSync struct {
	AutoSync *AutoSyncEvent `protobuf:"bytes,6,opt,name=auto_sync,json=autoSync,proto3,oneof"`
}

func (*Event_ConfigChange) isEvent_Payload() {}

func (*Event_SyncComplete) isEvent_Payload() {}

func (*Event_Error) isEvent_Payload() {}

func (*Event_AutoSync) isEvent_Payload() {}

type ConfigChangeEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChangeType      string                 `protobuf:"bytes,1,opt,name=change_type,json=changeType,proto3" json:"change_type,omitempty"`
	Source          string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	AffectedServers []string               `protobuf:"bytes,3,rep,name=affected_servers,json=affectedServers,proto3" json:"affected_servers,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConfigChangeEvent) Reset() {
	*x = ConfigChangeEvent{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigChangeEvent) ProtoMessage() {}

func (x *ConfigChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigChangeEvent.ProtoReflect.Descriptor instead.
func (*ConfigChangeEvent) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{35}
}

func (x *ConfigChangeEvent) GetChangeType() string {
	if x != nil {
		return x.ChangeType
	}
	return ""
}

func (x *ConfigChangeEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ConfigChangeEvent) GetAffectedServers() []string {
	if x != nil {
		return x.AffectedServers
	}
	return nil
}

type SyncCompleteEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Destination   string                 `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ServersSynced int32                  `protobuf:"varint,3,opt,name=servers_synced,json=serversSynced,proto3" json:"servers_synced,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncCompleteEvent) Reset() {
	*x = SyncCompleteEvent{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncCompleteEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncCompleteEvent) ProtoMessage() {}

func (x *SyncCompleteEvent) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncCompleteEvent.ProtoReflect.Descriptor instead.
func (*SyncCompleteEvent) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{36}
}

func (x *SyncCompleteEvent) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *SyncCompleteEvent) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncCompleteEvent) GetServersSynced() int32 {
	if x != nil {
		return x.ServersSynced
	}
	return 0
}

type ErrorEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Component     string                 `protobuf:"bytes,2,opt,name=component,proto3" json:"component,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorEvent) Reset() {
	*x = ErrorEvent{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorEvent) ProtoMessage() {}

func (x *ErrorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorEvent.ProtoReflect.Descriptor instead.
func (*ErrorEvent) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{37}
}

func (x *ErrorEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorEvent) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

type AutoSyncEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // started, stopped, triggered
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoSyncEvent) Reset() {
	*x = AutoSyncEvent{}
	mi := &file_daemon_proto_daemon_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoSyncEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoSyncEvent) ProtoMessage() {}

func (x *AutoSyncEvent) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_daemon_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoSyncEvent.ProtoReflect.Descriptor instead.
func (*AutoSyncEvent) Descriptor() ([]byte, []int) {
	return file_daemon_proto_daemon_proto_rawDescGZIP(), []int{38}
}

func (x *AutoSyncEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AutoSyncEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_daemon_proto_daemon_proto protoreflect.FileDescriptor

const file_daemon_proto_daemon_proto_rawDesc = "" +
	"\n" +
	"\x19daemon/proto/daemon.proto\x12\x06daemon\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xec\x02\n" +
	"\fServerConfig\x12\x1c\n" +
	"\ttransport\x18\x01 \x01(\tR\ttransport\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12/\n" +
	"\x03env\x18\x05 \x03(\v2\x1d.daemon.ServerConfig.EnvEntryR\x03env\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x12>\n" +
	"\bmetadata\x18\a \x03(\v2\".daemon.ServerConfig.MetadataEntryR\bmetadata\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdc\x01\n" +
	"\n" +
	"ServerInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\x06config\x18\x02 \x01(\v2\x14.daemon.ServerConfigR\x06config\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\"T\n" +
	"\x10AddServerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\x06config\x18\x02 \x01(\v2\x14.daemon.ServerConfigR\x06config\"W\n" +
	"\x13UpdateServerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\x06config\x18\x02 \x01(\v2\x14.daemon.ServerConfigR\x06config\")\n" +
	"\x13RemoveServerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"&\n" +
	"\x10GetServerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\")\n" +
	"\x13EnableServerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"*\n" +
	"\x14DisableServerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"B\n" +
	"\x12ListServersRequest\x12,\n" +
	"\x06filter\x18\x01 \x01(\v2\x14.daemon.ServerFilterR\x06filter\"\x8a\x01\n" +
	"\fServerFilter\x12!\n" +
	"\fenabled_only\x18\x01 \x01(\bR\venabledOnly\x12\x1c\n" +
	"\ttransport\x18\x02 \x01(\tR\ttransport\x12!\n" +
	"\fname_pattern\x18\x03 \x01(\tR\vnamePattern\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\"<\n" +
	"\x0eServerResponse\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.daemon.ServerInfoR\x06server\"C\n" +
	"\x13ListServersResponse\x12,\n" +
	"\aservers\x18\x01 \x03(\v2\x12.daemon.ServerInfoR\aservers\"\xf8\x01\n" +
	"\x1aRegisterDestinationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x04type\x18\x02 \x01(\x0e2\x17.daemon.DestinationTypeR\x04type\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12I\n" +
	"\aoptions\x18\x04 \x03(\v2/.daemon.RegisterDestinationRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\".\n" +
	"\x18RemoveDestinationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xcc\x01\n" +
	"\x18ListDestinationsResponse\x12V\n" +
	"\fdestinations\x18\x01 \x03(\v22.daemon.ListDestinationsResponse.DestinationsEntryR\fdestinations\x1aX\n" +
	"\x11DestinationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.daemon.DestinationInfoR\x05value:\x028\x01\"\x92\x01\n" +
	"\x0fDestinationInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x04type\x18\x02 \x01(\x0e2\x17.daemon.DestinationTypeR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1c\n" +
	"\tavailable\x18\x04 \x01(\bR\tavailable\"`\n" +
	"\rSyncToRequest\x12 \n" +
	"\vdestination\x18\x01 \x01(\tR\vdestination\x12-\n" +
	"\aoptions\x18\x02 \x01(\v2\x13.daemon.SyncOptionsR\aoptions\"j\n" +
	"\x15SyncToMultipleRequest\x12\"\n" +
	"\fdestinations\x18\x01 \x03(\tR\fdestinations\x12-\n" +
	"\aoptions\x18\x02 \x01(\v2\x13.daemon.SyncOptionsR\aoptions\"6\n" +
	"\x12PreviewSyncRequest\x12 \n" +
	"\vdestination\x18\x01 \x01(\tR\vdestination\"T\n" +
	"\vSyncOptions\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\x12\x16\n" +
	"\x06backup\x18\x02 \x01(\bR\x06backup\x12\x17\n" +
	"\adry_run\x18\x03 \x01(\bR\x06dryRun\"\xb9\x01\n" +
	"\n" +
	"SyncResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0eservers_synced\x18\x03 \x01(\x05R\rserversSynced\x12\x16\n" +
	"\x06errors\x18\x04 \x03(\tR\x06errors\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xe9\x01\n" +
	"\x0fMultiSyncResult\x12>\n" +
	"\aresults\x18\x01 \x03(\v2$.daemon.MultiSyncResult.ResultsEntryR\aresults\x12#\n" +
	"\rtotal_success\x18\x02 \x01(\x05R\ftotalSuccess\x12!\n" +
	"\ftotal_failed\x18\x03 \x01(\x05R\vtotalFailed\x1aN\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.daemon.SyncResultR\x05value:\x028\x01\"b\n" +
	"\vSyncPreview\x12.\n" +
	"\achanges\x18\x01 \x03(\v2\x14.daemon.ServerChangeR\achanges\x12#\n" +
	"\rtotal_changes\x18\x02 \x01(\x05R\ftotalChanges\"\xa4\x01\n" +
	"\fServerChange\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.daemon.ChangeTypeR\x04type\x12,\n" +
	"\x06before\x18\x03 \x01(\v2\x14.daemon.ServerConfigR\x06before\x12*\n" +
	"\x05after\x18\x04 \x01(\v2\x14.daemon.ServerConfigR\x05after\"\x81\x02\n" +
	"\x0eAutoSyncConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12*\n" +
	"\x11watch_interval_ms\x18\x02 \x01(\x03R\x0fwatchIntervalMs\x12*\n" +
	"\x11debounce_delay_ms\x18\x03 \x01(\x03R\x0fdebounceDelayMs\x12)\n" +
	"\x10target_whitelist\x18\x04 \x03(\tR\x0ftargetWhitelist\x12)\n" +
	"\x10target_blacklist\x18\x05 \x03(\tR\x0ftargetBlacklist\x12'\n" +
	"\x0fignore_patterns\x18\x06 \x03(\tR\x0eignorePatterns\"\xc8\x01\n" +
	"\x0eAutoSyncStatus\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x18\n" +
	"\arunning\x18\x02 \x01(\bR\arunning\x127\n" +
	"\tlast_sync\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\blastSync\x12*\n" +
	"\x11watch_interval_ms\x18\x04 \x01(\x03R\x0fwatchIntervalMs\x12\x1d\n" +
	"\n" +
	"last_error\x18\x05 \x01(\tR\tlastError\"\xd9\x01\n" +
	"\x06Config\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x125\n" +
	"\aservers\x18\x02 \x03(\v2\x1b.daemon.Config.ServersEntryR\aservers\x12,\n" +
	"\bsettings\x18\x03 \x01(\v2\x10.daemon.SettingsR\bsettings\x1aP\n" +
	"\fServersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.daemon.ServerConfigR\x05value:\x028\x01\"\xad\x01\n" +
	"\bSettings\x125\n" +
	"\tauto_sync\x18\x01 \x01(\v2\x18.daemon.AutoSyncSettingsR\bautoSync\x12.\n" +
	"\x06backup\x18\x02 \x01(\v2\x16.daemon.BackupSettingsR\x06backup\x12:\n" +
	"\n" +
	"validation\x18\x03 \x01(\v2\x1a.daemon.ValidationSettingsR\n" +
	"validation\"\x84\x01\n" +
	"\x10AutoSyncSettings\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12*\n" +
	"\x11watch_interval_ms\x18\x02 \x01(\x03R\x0fwatchIntervalMs\x12*\n" +
	"\x11debounce_delay_ms\x18\x03 \x01(\x03R\x0fdebounceDelayMs\"g\n" +
	"\x0eBackupSettings\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\x12\x1f\n" +
	"\vmax_backups\x18\x03 \x01(\x05R\n" +
	"maxBackups\"O\n" +
	"\x12ValidationSettings\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1f\n" +
	"\vstrict_mode\x18\x02 \x01(\bR\n" +
	"strictMode\"'\n" +
	"\x11LoadConfigRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x9e\x02\n" +
	"\fDaemonStatus\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds\x12-\n" +
	"\x12active_connections\x18\x05 \x01(\x05R\x11activeConnections\x12*\n" +
	"\x11auto_sync_running\x18\x06 \x01(\bR\x0fautoSyncRunning\x12\x1d\n" +
	"\n" +
	"last_error\x18\a \x01(\tR\tlastError\";\n" +
	"\x10SubscribeRequest\x12'\n" +
	"\x05types\x18\x01 \x03(\x0e2\x11.daemon.EventTypeR\x05types\"\xd9\x02\n" +
	"\x05Event\x12%\n" +
	"\x04type\x18\x01 \x01(\x0e2\x11.daemon.EventTypeR\x04type\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12@\n" +
	"\rconfig_change\x18\x03 \x01(\v2\x19.daemon.ConfigChangeEventH\x00R\fconfigChange\x12@\n" +
	"\rsync_complete\x18\x04 \x01(\v2\x19.daemon.SyncCompleteEventH\x00R\fsyncComplete\x12*\n" +
	"\x05error\x18\x05 \x01(\v2\x12.daemon.ErrorEventH\x00R\x05error\x124\n" +
	"\tauto_sync\x18\x06 \x01(\v2\x15.daemon.AutoSyncEventH\x00R\bautoSyncB\t\n" +
	"\apayload\"w\n" +
	"\x11ConfigChangeEvent\x12\x1f\n" +
	"\vchange_type\x18\x01 \x01(\tR\n" +
	"changeType\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12)\n" +
	"\x10affected_servers\x18\x03 \x03(\tR\x0faffectedServers\"v\n" +
	"\x11SyncCompleteEvent\x12 \n" +
	"\vdestination\x18\x01 \x01(\tR\vdestination\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12%\n" +
	"\x0eservers_synced\x18\x03 \x01(\x05R\rserversSynced\"D\n" +
	"\n" +
	"ErrorEvent\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1c\n" +
	"\tcomponent\x18\x02 \x01(\tR\tcomponent\"A\n" +
	"\rAutoSyncEvent\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*b\n" +
	"\x0fDestinationType\x12\b\n" +
	"\x04FILE\x10\x00\x12\n" +
	"\n" +
	"\x06CLAUDE\x10\x01\x12\n" +
	"\n" +
	"\x06VSCODE\x10\x02\x12\n" +
	"\n" +
	"\x06CURSOR\x10\x03\x12\f\n" +
	"\bWINDSURF\x10\x04\x12\a\n" +
	"\x03ZED\x10\x05\x12\n" +
	"\n" +
	"\x06CUSTOM\x10c*<\n" +
	"\n" +
	"ChangeType\x12\a\n" +
	"\x03ADD\x10\x00\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x01\x12\n" +
	"\n" +
	"\x06REMOVE\x10\x02\x12\r\n" +
	"\tNO_CHANGE\x10\x03*R\n" +
	"\tEventType\x12\x11\n" +
	"\rCONFIG_CHANGE\x10\x00\x12\x11\n" +
	"\rSYNC_COMPLETE\x10\x01\x12\t\n" +
	"\x05ERROR\x10\x02\x12\x14\n" +
	"\x10AUTO_SYNC_STATUS\x10\x032\xfc\v\n" +
	"\x11AgentMasterDaemon\x12=\n" +
	"\tAddServer\x12\x18.daemon.AddServerRequest\x1a\x16.daemon.ServerResponse\x12C\n" +
	"\fUpdateServer\x12\x1b.daemon.UpdateServerRequest\x1a\x16.daemon.ServerResponse\x12C\n" +
	"\fRemoveServer\x12\x1b.daemon.RemoveServerRequest\x1a\x16.google.protobuf.Empty\x12=\n" +
	"\tGetServer\x12\x18.daemon.GetServerRequest\x1a\x16.daemon.ServerResponse\x12F\n" +
	"\vListServers\x12\x1a.daemon.ListServersRequest\x1a\x1b.daemon.ListServersResponse\x12C\n" +
	"\fEnableServer\x12\x1b.daemon.EnableServerRequest\x1a\x16.daemon.ServerResponse\x12E\n" +
	"\rDisableServer\x12\x1c.daemon.DisableServerRequest\x1a\x16.daemon.ServerResponse\x12Q\n" +
	"\x13RegisterDestination\x12\".daemon.RegisterDestinationRequest\x1a\x16.google.protobuf.Empty\x12M\n" +
	"\x11RemoveDestination\x12 .daemon.RemoveDestinationRequest\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\x10ListDestinations\x12\x16.google.protobuf.Empty\x1a .daemon.ListDestinationsResponse\x123\n" +
	"\x06SyncTo\x12\x15.daemon.SyncToRequest\x1a\x12.daemon.SyncResult\x12H\n" +
	"\x0eSyncToMultiple\x12\x1d.daemon.SyncToMultipleRequest\x1a\x17.daemon.MultiSyncResult\x12>\n" +
	"\vPreviewSync\x12\x1a.daemon.PreviewSyncRequest\x1a\x13.daemon.SyncPreview\x12?\n" +
	"\rStartAutoSync\x12\x16.daemon.AutoSyncConfig\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\fStopAutoSync\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12C\n" +
	"\x11GetAutoSyncStatus\x12\x16.google.protobuf.Empty\x1a\x16.daemon.AutoSyncStatus\x123\n" +
	"\tGetConfig\x12\x16.google.protobuf.Empty\x1a\x0e.daemon.Config\x123\n" +
	"\tSetConfig\x12\x0e.daemon.Config\x1a\x16.google.protobuf.Empty\x12?\n" +
	"\n" +
	"LoadConfig\x12\x19.daemon.LoadConfigRequest\x1a\x16.google.protobuf.Empty\x12<\n" +
	"\n" +
	"SaveConfig\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x129\n" +
	"\tGetStatus\x12\x16.google.protobuf.Empty\x1a\x14.daemon.DaemonStatus\x12:\n" +
	"\bShutdown\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x126\n" +
	"\tSubscribe\x12\x18.daemon.SubscribeRequest\x1a\r.daemon.Event0\x01B7Z5github.com/b-open-io/agent-master-engine/daemon/protob\x06proto3"

var (
	file_daemon_proto_daemon_proto_rawDescOnce sync.Once
	file_daemon_proto_daemon_proto_rawDescData []byte
)

func file_daemon_proto_daemon_proto_rawDescGZIP() []byte {
	file_daemon_proto_daemon_proto_rawDescOnce.Do(func() {
		file_daemon_proto_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_daemon_proto_daemon_proto_rawDesc), len(file_daemon_proto_daemon_proto_rawDesc)))
	})
	return file_daemon_proto_daemon_proto_rawDescData
}

var file_daemon_proto_daemon_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_daemon_proto_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 45)
var file_daemon_proto_daemon_proto_goTypes = []any{
	(DestinationType)(0),               // 0: daemon.DestinationType
	(ChangeType)(0),                    // 1: daemon.ChangeType
	(EventType)(0),                     // 2: daemon.EventType
	(*ServerConfig)(nil),               // 3: daemon.ServerConfig
	(*ServerInfo)(nil),                 // 4: daemon.ServerInfo
	(*AddServerRequest)(nil),           // 5: daemon.AddServerRequest
	(*UpdateServerRequest)(nil),        // 6: daemon.UpdateServerRequest
	(*RemoveServerRequest)(nil),        // 7: daemon.RemoveServerRequest
	(*GetServerRequest)(nil),           // 8: daemon.GetServerRequest
	(*EnableServerRequest)(nil),        // 9: daemon.EnableServerRequest
	(*DisableServerRequest)(nil),       // 10: daemon.DisableServerRequest
	(*ListServersRequest)(nil),         // 11: daemon.ListServersRequest
	(*ServerFilter)(nil),               // 12: daemon.ServerFilter
	(*ServerResponse)(nil),             // 13: daemon.ServerResponse
	(*ListServersResponse)(nil),        // 14: daemon.ListServersResponse
	(*RegisterDestinationRequest)(nil), // 15: daemon.RegisterDestinationRequest
	(*RemoveDestinationRequest)(nil),   // 16: daemon.RemoveDestinationRequest
	(*ListDestinationsResponse)(nil),   // 17: daemon.ListDestinationsResponse
	(*DestinationInfo)(nil),            // 18: daemon.DestinationInfo
	(*SyncToRequest)(nil),              // 19: daemon.SyncToRequest
	(*SyncToMultipleRequest)(nil),      // 20: daemon.SyncToMultipleRequest
	(*PreviewSyncRequest)(nil),         // 21: daemon.PreviewSyncRequest
	(*SyncOptions)(nil),                // 22: daemon.SyncOptions
	(*SyncResult)(nil),                 // 23: daemon.SyncResult
	(*MultiSyncResult)(nil),            // 24: daemon.MultiSyncResult
	(*SyncPreview)(nil),                // 25: daemon.SyncPreview
	(*ServerChange)(nil),               // 26: daemon.ServerChange
	(*AutoSyncConfig)(nil),             // 27: daemon.AutoSyncConfig
	(*AutoSyncStatus)(nil),             // 28: daemon.AutoSyncStatus
	(*Config)(nil),                     // 29: daemon.Config
	(*Settings)(nil),                   // 30: daemon.Settings
	(*AutoSyncSettings)(nil),           // 31: daemon.AutoSyncSettings
	(*BackupSettings)(nil),             // 32: daemon.BackupSettings
	(*ValidationSettings)(nil),         // 33: daemon.ValidationSettings
	(*LoadConfigRequest)(nil),          // 34: daemon.LoadConfigRequest
	(*DaemonStatus)(nil),               // 35: daemon.DaemonStatus
	(*SubscribeRequest)(nil),           // 36: daemon.SubscribeRequest
	(*Event)(nil),                      // 37: daemon.Event
	(*ConfigChangeEvent)(nil),          // 38: daemon.ConfigChangeEvent
	(*SyncCompleteEvent)(nil),          // 39: daemon.SyncCompleteEvent
	(*ErrorEvent)(nil),                 // 40: daemon.ErrorEvent
	(*AutoSyncEvent)(nil),              // 41: daemon.AutoSyncEvent
	nil,                                // 42: daemon.ServerConfig.EnvEntry
	nil,                                // 43: daemon.ServerConfig.MetadataEntry
	nil,                                // 44: daemon.RegisterDestinationRequest.OptionsEntry
	nil,                                // 45: daemon.ListDestinationsResponse.DestinationsEntry
	nil,                                // 46: daemon.MultiSyncResult.ResultsEntry
	nil,                                // 47: daemon.Config.ServersEntry
	(*timestamppb.Timestamp)(nil),      // 48: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 49: google.protobuf.Empty
}
var file_daemon_proto_daemon_proto_depIdxs = []int32{
	42, // 0: daemon.ServerConfig.env:type_name -> daemon.ServerConfig.EnvEntry
	43, // 1: daemon.ServerConfig.metadata:type_name -> daemon.ServerConfig.MetadataEntry
	3,  // 2: daemon.ServerInfo.config:type_name -> daemon.ServerConfig
	48, // 3: daemon.ServerInfo.created_at:type_name -> google.protobuf.Timestamp
	48, // 4: daemon.ServerInfo.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 5: daemon.AddServerRequest.config:type_name -> daemon.ServerConfig
	3,  // 6: daemon.UpdateServerRequest.config:type_name -> daemon.ServerConfig
	12, // 7: daemon.ListServersRequest.filter:type_name -> daemon.ServerFilter
	4,  // 8: daemon.ServerResponse.server:type_name -> daemon.ServerInfo
	4,  // 9: daemon.ListServersResponse.servers:type_name -> daemon.ServerInfo
	0,  // 10: daemon.RegisterDestinationRequest.type:type_name -> daemon.DestinationType
	44, // 11: daemon.RegisterDestinationRequest.options:type_name -> daemon.RegisterDestinationRequest.OptionsEntry
	45, // 12: daemon.ListDestinationsResponse.destinations:type_name -> daemon.ListDestinationsResponse.DestinationsEntry
	0,  // 13: daemon.DestinationInfo.type:type_name -> daemon.DestinationType
	22, // 14: daemon.SyncToRequest.options:type_name -> daemon.SyncOptions
	22, // 15: daemon.SyncToMultipleRequest.options:type_name -> daemon.SyncOptions
	48, // 16: daemon.SyncResult.timestamp:type_name -> google.protobuf.Timestamp
	46, // 17: daemon.MultiSyncResult.results:type_name -> daemon.MultiSyncResult.ResultsEntry
	26, // 18: daemon.SyncPreview.changes:type_name -> daemon.ServerChange
	1,  // 19: daemon.ServerChange.type:type_name -> daemon.ChangeType
	3,  // 20: daemon.ServerChange.before:type_name -> daemon.ServerConfig
	3,  // 21: daemon.ServerChange.after:type_name -> daemon.ServerConfig
	48, // 22: daemon.AutoSyncStatus.last_sync:type_name -> google.protobuf.Timestamp
	47, // 23: daemon.Config.servers:type_name -> daemon.Config.ServersEntry
	30, // 24: daemon.Config.settings:type_name -> daemon.Settings
	31, // 25: daemon.Settings.auto_sync:type_name -> daemon.AutoSyncSettings
	32, // 26: daemon.Settings.backup:type_name -> daemon.BackupSettings
	33, // 27: daemon.Settings.validation:type_name -> daemon.ValidationSettings
	48, // 28: daemon.DaemonStatus.start_time:type_name -> google.protobuf.Timestamp
	2,  // 29: daemon.SubscribeRequest.types:type_name -> daemon.EventType
	2,  // 30: daemon.Event.type:type_name -> daemon.EventType
	48, // 31: daemon.Event.timestamp:type_name -> google.protobuf.Timestamp
	38, // 32: daemon.Event.config_change:type_name -> daemon.ConfigChangeEvent
	39, // 33: daemon.Event.sync_complete:type_name -> daemon.SyncCompleteEvent
	40, // 34: daemon.Event.error:type_name -> daemon.ErrorEvent
	41, // 35: daemon.Event.auto_sync:type_name -> daemon.AutoSyncEvent
	18, // 36: daemon.ListDestinationsResponse.DestinationsEntry.value:type_name -> daemon.DestinationInfo
	23, // 37: daemon.MultiSyncResult.ResultsEntry.value:type_name -> daemon.SyncResult
	3,  // 38: daemon.Config.ServersEntry.value:type_name -> daemon.ServerConfig
	5,  // 39: daemon.AgentMasterDaemon.AddServer:input_type -> daemon.AddServerRequest
	6,  // 40: daemon.AgentMasterDaemon.UpdateServer:input_type -> daemon.UpdateServerRequest
	7,  // 41: daemon.AgentMasterDaemon.RemoveServer:input_type -> daemon.RemoveServerRequest
	8,  // 42: daemon.AgentMasterDaemon.GetServer:input_type -> daemon.GetServerRequest
	11, // 43: daemon.AgentMasterDaemon.ListServers:input_type -> daemon.ListServersRequest
	9,  // 44: daemon.AgentMasterDaemon.EnableServer:input_type -> daemon.EnableServerRequest
	10, // 45: daemon.AgentMasterDaemon.DisableServer:input_type -> daemon.DisableServerRequest
	15, // 46: daemon.AgentMasterDaemon.RegisterDestination:input_type -> daemon.RegisterDestinationRequest
	16, // 47: daemon.AgentMasterDaemon.RemoveDestination:input_type -> daemon.RemoveDestinationRequest
	49, // 48: daemon.AgentMasterDaemon.ListDestinations:input_type -> google.protobuf.Empty
	19, // 49: daemon.AgentMasterDaemon.SyncTo:input_type -> daemon.SyncToRequest
	20, // 50: daemon.AgentMasterDaemon.SyncToMultiple:input_type -> daemon.SyncToMultipleRequest
	21, // 51: daemon.AgentMasterDaemon.PreviewSync:input_type -> daemon.PreviewSyncRequest
	27, // 52: daemon.AgentMasterDaemon.StartAutoSync:input_type -> daemon.AutoSyncConfig
	49, // 53: daemon.AgentMasterDaemon.StopAutoSync:input_type -> google.protobuf.Empty
	49, // 54: daemon.AgentMasterDaemon.GetAutoSyncStatus:input_type -> google.protobuf.Empty
	49, // 55: daemon.AgentMasterDaemon.GetConfig:input_type -> google.protobuf.Empty
	29, // 56: daemon.AgentMasterDaemon.SetConfig:input_type -> daemon.Config
	34, // 57: daemon.AgentMasterDaemon.LoadConfig:input_type -> daemon.LoadConfigRequest
	49, // 58: daemon.AgentMasterDaemon.SaveConfig:input_type -> google.protobuf.Empty
	49, // 59: daemon.AgentMasterDaemon.GetStatus:input_type -> google.protobuf.Empty
	49, // 60: daemon.AgentMasterDaemon.Shutdown:input_type -> google.protobuf.Empty
	36, // 61: daemon.AgentMasterDaemon.Subscribe:input_type -> daemon.SubscribeRequest
	13, // 62: daemon.AgentMasterDaemon.AddServer:output_type -> daemon.ServerResponse
	13, // 63: daemon.AgentMasterDaemon.UpdateServer:output_type -> daemon.ServerResponse
	49, // 64: daemon.AgentMasterDaemon.RemoveServer:output_type -> google.protobuf.Empty
	13, // 65: daemon.AgentMasterDaemon.GetServer:output_type -> daemon.ServerResponse
	14, // 66: daemon.AgentMasterDaemon.ListServers:output_type -> daemon.ListServersResponse
	13, // 67: daemon.AgentMasterDaemon.EnableServer:output_type -> daemon.ServerResponse
	13, // 68: daemon.AgentMasterDaemon.DisableServer:output_type -> daemon.ServerResponse
	49, // 69: daemon.AgentMasterDaemon.RegisterDestination:output_type -> google.protobuf.Empty
	49, // 70: daemon.AgentMasterDaemon.RemoveDestination:output_type -> google.protobuf.Empty
	17, // 71: daemon.AgentMasterDaemon.ListDestinations:output_type -> daemon.ListDestinationsResponse
	23, // 72: daemon.AgentMasterDaemon.SyncTo:output_type -> daemon.SyncResult
	24, // 73: daemon.AgentMasterDaemon.SyncToMultiple:output_type -> daemon.MultiSyncResult
	25, // 74: daemon.AgentMasterDaemon.PreviewSync:output_type -> daemon.SyncPreview
	49, // 75: daemon.AgentMasterDaemon.StartAutoSync:output_type -> google.protobuf.Empty
	49, // 76: daemon.AgentMasterDaemon.StopAutoSync:output_type -> google.protobuf.Empty
	28, // 77: daemon.AgentMasterDaemon.GetAutoSyncStatus:output_type -> daemon.AutoSyncStatus
	29, // 78: daemon.AgentMasterDaemon.GetConfig:output_type -> daemon.Config
	49, // 79: daemon.AgentMasterDaemon.SetConfig:output_type -> google.protobuf.Empty
	49, // 80: daemon.AgentMasterDaemon.LoadConfig:output_type -> google.protobuf.Empty
	49, // 81: daemon.AgentMasterDaemon.SaveConfig:output_type -> google.protobuf.Empty
	35, // 82: daemon.AgentMasterDaemon.GetStatus:output_type -> daemon.DaemonStatus
	49, // 83: daemon.AgentMasterDaemon.Shutdown:output_type -> google.protobuf.Empty
	37, // 84: daemon.AgentMasterDaemon.Subscribe:output_type -> daemon.Event
	62, // [62:85] is the sub-list for method output_type
	39, // [39:62] is the sub-list for method input_type
	39, // [39:39] is the sub-list for extension type_name
	39, // [39:39] is the sub-list for extension extendee
	0,  // [0:39] is the sub-list for field type_name
}

func init() { file_daemon_proto_daemon_proto_init() }
func file_daemon_proto_daemon_proto_init() {
	if File_daemon_proto_daemon_proto != nil {
		return
	}
	file_daemon_proto_daemon_proto_msgTypes[34].OneofWrappers = []any{
		(*Event_ConfigChange)(nil),
		(*Event_SyncComplete)(nil),
		(*Event_Error)(nil),
		(*Event_AutoSync)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_daemon_proto_daemon_proto_rawDesc), len(file_daemon_proto_daemon_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   45,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_daemon_proto_daemon_proto_goTypes,
		DependencyIndexes: file_daemon_proto_daemon_proto_depIdxs,
		EnumInfos:         file_daemon_proto_daemon_proto_enumTypes,
		MessageInfos:      file_daemon_proto_daemon_proto_msgTypes,
	}.Build()
	File_daemon_proto_daemon_proto = out.File
	file_daemon_proto_daemon_proto_goTypes = nil
	file_daemon_proto_daemon_proto_depIdxs = nil
}
